# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Generating normal distribution using Rcpp
#' @description Generating normal distribution using Rcpp
#' @param n the number of sample (numeric)
#' @param sigma the standard deviation of the  norm distribution (numeric)
#' @return a normal distribution sample of size \code{n}
#' @examples
#' \dontrun{
#' random(1,100)
#' }
#' @export
random <- function(sigma, n) {
    .Call('_StatComp20013_random', PACKAGE = 'StatComp20013', sigma, n)
}

#' @title Use random walk to get Markov chain  using Rcpp.
#' @description Use random walk to get Markov chain  using Rcpp.
#' @param sig the standard deviation of the  norm distribution (numeric)
#' @param n1 the number of sample (numeric)
#' @return a Markov chain of size \code{n1} and the accept rate
#' @examples
#' \dontrun{
#' chain(1,1000)
#' }
#' @export
chain <- function(sig, n1) {
    .Call('_StatComp20013_chain', PACKAGE = 'StatComp20013', sig, n1)
}

